from openai import OpenAI
from .config import SETTINGS

_client = OpenAI(api_key=SETTINGS.openai_api_key)

def ask_llm(prompt: str) -> str:
    """
    Sends a prompt to the configured LLM (Large Language Model) and returns the generated response.

    Args:
      prompt (str): The input prompt or question to send to the LLM.

    Returns:
      str: The text output generated by the LLM in response to the prompt.

    Note:
      - Assumes that `_client` and `SETTINGS.llm_model` are properly initialized and configured.
      - The function expects the LLM client to have a `responses.create` method and the response object to have an `output_text` attribute.
    """
    resp = _client.responses.create(
        model=SETTINGS.llm_model,
        input=prompt
    )
    return resp.output_text
